# Generated by Django 4.0.1 on 2022-02-14 04:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GameMod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_mod', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='store_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=10)),
                ('time', models.PositiveIntegerField()),
                ('ans', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('day', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='headshot/')),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sort_term_memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_rate', models.IntegerField()),
                ('memoryTime', models.IntegerField()),
                ('costTime', models.IntegerField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.gamemod')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_rate', models.IntegerField()),
                ('memoryTime', models.IntegerField()),
                ('costTime', models.IntegerField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.gamemod')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
        migrations.AddField(
            model_name='gamemod',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.userdata'),
        ),
        migrations.CreateModel(
            name='Attention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_rate', models.IntegerField()),
                ('add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='robot.gamemod')),
            ],
            options={
                'ordering': ['-add_time'],
            },
        ),
    ]
